### ISSUE TITLE
[1.18] [Bug] KubeJS recipe sync issue

### ISSUE THREAD

**Issue by Water-Moon** [Low-Drag-MC/Multiblocked#68]
In 1.18, recipes added through KubeJS using `event.recipes.multiblocked.multiblock` will not display for any clients connecting to a server. The recipe still work as intended on the server, but JEI or REI will not show the recipe.
Further more, if predicates are used, in particular `.dimension` requirement, there will be reports about "non [0-9a-Z] character in registry name", and all player will fail to sync datapack, while the console is filled with spam of non-ascii characters, like the one shown below.
![image](https://user-images.githubusercontent.com/43123946/236648718-f3fff493-6ee0-4ea7-bd81-136f9577a046.png)

**Comment by DarkeFae** [comment]
I am also running into this issue, and as Water-Moon said, it appears to be the dimension requirement.

here is a copy of my server log: [Log](https://github.com/DarkeFae/crash-reports/blob/main/Multiblock%20Madness%202/2023-06-16-3.log)
The errors are line 16029 (sorry the log is so long..)

EDIT:
forgot to include my mod information..
Mbd version: 1.18.2-1.0.5
Forge/MC version: 1.18.2-40.2.1

**Comment by Yefancy** [comment]
fixed in the next update

**Comment by Frefreak** [comment]
Could you please confirm if the recipe sync issue has also been fixed with this update?

**Comment by DarkeFae** [comment]
@Frefreak Yup, was actually just testing this the other day for someone. Working fine now.

**Comment by Frefreak** [comment]
> @Frefreak Yup, was actually just testing this the other day for someone. Working fine now.

Thanks for the confirmation. I'm still experiencing the "recipe not showing up in multiplayer" issue, maybe I need to have a further testing in a clean env myself.

**Comment by DarkeFae** [comment]
> Thanks for the confirmation. I'm still experiencing the "recipe not showing up in multiplayer" issue, maybe I need to have a further testing in a clean env myself.

Yeah i just realized we are both working on multiblock madness 2 servers from your talk in filo's issues chat
